- name: "Ursula Status"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:
    - name: Get public ip
      uri:
        url: http://ifconfig.me/ip
        return_content: yes
      register: ip_response

    - name: "Request Ursula Status"
      become: yes
      uri:
        url: "https://{{ip_response.content}}:9151/status/?json=true"
        validate_certs: no
      register: status_data

    - name: Print Result
      debug:
        msg:
          - "{{status_data.json.nickname}}"
          - "nucypher version:      {{status_data.json.version}}"
          - "staker address:        {{status_data.json.staker_address}}"
          - "worker address:        {{status_data.json.worker_address}}"
          - "rest url:              https://{{status_data.json.rest_url}}"
          - "missing commitments:   {{status_data.json.missing_commitments}}"
          - "last committed period: {{status_data.json.last_committed_period}}"
          - "balances:"
          - "   ETH:                {{status_data.json.balances.eth}}"
          - "   NU:                 {{status_data.json.balances.nu}}"
