version: '3'

services:
  nucypher-dev:
    volumes:
      - ../..:/code
    ports:
      - 10151:10151
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile
    image: dev:nucypher
    container_name: nucypher-dev
    working_dir: /code
    environment:
      - PYTHONBREAKPOINT=ipdb.set_trace
